
 export const REQUEST_PEOPLE_PENDING = 'PENDING';
 export const REQUEST_PEOPLE_SUCCESS = 'SUCCESS';
 export const REQUEST_PEOPLE_FAILED = 'FAILED';
 export const CHARACTER_COUNTER_CLICKED = 'CHARACTER_COUNTER_CLICKED';